In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Advertising_cleaned.csv')
df

     sales  total_spend
0    22100       337100
1    10400       128900
2     9300       132400
3    18500       251300
4    12900       250000
..     ...          ...
195   7600        55700
196   9700       107200
197  12800       192700
198  25500       391800
199  13400       249400

[200 rows x 2 columns]

In [10]:
X = df[['total_spend']]
y=df['sales']

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# GridSearchCV

In [16]:
from sklearn.model_selection import GridSearchCV 

from sklearn.linear_model import Ridge 
estimator = Ridge()

param_grid = {'alpha':list(range(1,100))}

r_gs = GridSearchCV(estimator,param_grid,scoring='r2',cv=5)
r_gs.fit(X_train,y_train)
r_gs.best_estimator_

Ridge(alpha=99)

In [12]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=99)
model.fit(X_train,y_train)

Ridge(alpha=99)

In [13]:
print('COeff:',model.coef_)
print('Intercept:',model.intercept_)

COeff: [0.04699098]
Intercept: 4629.8432567531545

In [14]:
y_pred_train = model.predict(X_train)
from sklearn.metrics import r2_score 
print('Train R2:',r2_score(y_train,y_pred_train))

Train R2: 0.7324155261123497

In [15]:
ypred_test = model.predict(X_test)
print('Test r2:',r2_score(y_test,ypred_test))

Test r2: 0.8099382126930932

In [17]:
from sklearn.model_selection import GridSearchCV 

from sklearn.linear_model import Lasso
estimator = Lasso()

param_grid = {'alpha':list(range(1,100))}

lasso_gs = GridSearchCV(estimator,param_grid,scoring='r2',cv=5)
lasso_gs.fit(X_train,y_train)
lasso_gs.best_estimator_

Lasso(alpha=99)

In [18]:
from sklearn.linear_model import Lasso 
model = Lasso(alpha=99)
model.fit(X_train,y_train)

Lasso(alpha=99)

In [19]:
print('COeff:',model.coef_)
print('Intercept:',model.intercept_)

COeff: [0.04699096]
Intercept: 4629.845616483986

In [20]:
y_pred_train = model.predict(X_train)
from sklearn.metrics import r2_score 
print('Train R2:',r2_score(y_train,y_pred_train))

Train R2: 0.7324155261123053

In [21]:
ypred_test = model.predict(X_test)
print('Test r2:',r2_score(y_test,ypred_test))

Test r2: 0.8099381585055405

In [25]:
from sklearn.model_selection import GridSearchCV 

from sklearn.linear_model import ElasticNet
estimator = ElasticNet()

param_grid = {'alpha':list(range(1,70))}

el_gs = GridSearchCV(estimator,param_grid,scoring='r2',cv=5)
el_gs.fit(X_train,y_train)
el_gs.best_estimator_

ElasticNet(alpha=69)

In [30]:
from sklearn.linear_model import ElasticNet
model = ElasticNet(alpha=59,l1_ratio=0.5)
model.fit(X_train,y_train)

ElasticNet(alpha=59)

In [31]:
print('COeff:',model.coef_)
print('Intercept:',model.intercept_)

COeff: [0.04699097]
Intercept: 4629.843992470109

In [32]:
y_pred_train = model.predict(X_train)
from sklearn.metrics import r2_score 
print('Train R2:',r2_score(y_train,y_pred_train))

Train R2: 0.7324155261123454

In [33]:
ypred_test = model.predict(X_test)
print('Test r2:',r2_score(y_test,ypred_test))

Test r2: 0.8099381957985043

# polynomial Regression

In [34]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=77)

In [35]:
from sklearn.preprocessing import PolynomialFeatures 
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))

In [36]:
X_train_poly

            0             1             2
0    237500.0  5.640625e+10  1.339648e+16
1    162800.0  2.650384e+10  4.314825e+15
2    132600.0  1.758276e+10  2.331474e+15
3    113800.0  1.295044e+10  1.473760e+15
4    159500.0  2.544025e+10  4.057720e+15
..        ...           ...           ...
155  184700.0  3.411409e+10  6.300872e+15
156  235100.0  5.527201e+10  1.299445e+16
157  169800.0  2.883204e+10  4.895680e+15
158  290300.0  8.427409e+10  2.446477e+16
159  247800.0  6.140484e+10  1.521612e+16

[160 rows x 3 columns]

In [37]:
X_test_poly

           0             1             2
0    89400.0  7.992360e+09  7.145170e+14
1   218400.0  4.769856e+10  1.041737e+16
2   299500.0  8.970025e+10  2.686522e+16
3   148500.0  2.205225e+10  3.274759e+15
4   292900.0  8.579041e+10  2.512801e+16
5   115400.0  1.331716e+10  1.536800e+15
6   113900.0  1.297321e+10  1.477649e+15
7    80000.0  6.400000e+09  5.120000e+14
8   251100.0  6.305121e+10  1.583216e+16
9   170100.0  2.893401e+10  4.921675e+15
10  238900.0  5.707321e+10  1.363479e+16
11   91100.0  8.299210e+09  7.560580e+14
12  112300.0  1.261129e+10  1.416248e+15
13  376800.0  1.419782e+11  5.349740e+16
14  212400.0  4.511376e+10  9.582163e+15
15  218400.0  4.769856e+10  1.041737e+16
16  298100.0  8.886361e+10  2.649024e+16
17   11700.0  1.368900e+08  1.601613e+12
18   91600.0  8.390560e+09  7.685753e+14
19   92300.0  8.519290e+09  7.863305e+14
20   77100.0  5.944410e+09  4.583140e+14
21   54200.0  2.937640e+09  1.592201e+14
22  296000.0  8.761600e+10  2.593434e+16
23  187900.0  3.530641e+10  6.634074e+15
24  164000.0  2.689600e+10  4.410944e+15
25  249400.0  6.220036e+10  1.551277e+16
26  298900.0  8.934121e+10  2.670409e+16
27  302900.0  9.174841e+10  2.779059e+16
28  168200.0  2.829124e+10  4.758587e+15
29  277300.0  7.689529e+10  2.132306e+16
30  287900.0  8.288641e+10  2.386300e+16
31  241700.0  5.841889e+10  1.411985e+16
32  188300.0  3.545689e+10  6.676532e+15
33  207700.0  4.313929e+10  8.960031e+15
34  170800.0  2.917264e+10  4.982687e+15
35   78700.0  6.193690e+09  4.874434e+14
36  184800.0  3.415104e+10  6.311112e+15
37  242000.0  5.856400e+10  1.417249e+16
38   21400.0  4.579600e+08  9.800344e+12
39  178100.0  3.171961e+10  5.649263e+15

In [40]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()
model.fit(X_train_poly,y_train)

LinearRegression()

In [41]:
print('coeffs:',model.coef_)
print('Intercept:',model.intercept_)

coeffs: [ 8.59564389e-02 -2.09463379e-07  3.32634930e-13]
Intercept: 2540.5822494728964

In [42]:
ypred_train = model.predict(X_train_poly)
from sklearn.metrics import r2_score 
print('Train r2:',r2_score(y_train,ypred_train))

Train r2: 0.7469025465324366

In [43]:
ypred_test = model.predict(X_test_poly)
print('Test R2:',r2_score(y_test,ypred_test))

Test R2: 0.7890225593074562